CREATE TABLE IF NOT EXIST PRODUCTS ( 
    PRODUCT_ID TEXT,
    PRODUCT_NAME TEXT, 
    SUPPLIER_ID TEXT , 
    UNIT TEXTT, 
    PRICE REAL
);

INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAAME, SUPPLIER_ID, CATEGORY_ID)