CREATE TABLE IF NOT EXISTS NOBEL_WIN( 
    YEAR INTEGER, 
    SUBJECT TEXT, 
    WINNER TEXT , 
    COUNTRY TEXT, 
    CATEGORY TEXT, 
);

INSERT INTO NOBEL_WIN (YEAR, SUBJECY, WINNER, COUNTRY, CATEGORY) VALUES
    (1875, 'PHYSICS', 'ALBERT ', 'SCIENTIST ')
    (1975, 'PHYSICS', 'ANDREW ', 'SCIENTIST ')
    (1865, 'PHYSICS', 'HAWKINS ', 'SCIENTIST ')
    (1855, 'PHYSICS', 'THOMAS ', 'SCIENTIST ')
    (1775, 'PHYSICS', 'JOSHUA ', 'SCIENTIST ')

    SELECT *
    FROM NOBEL_WIN
    WHERE SUBJECT NOT LIKE 'P%';